# Docker image for my code location. The build is a multi-stage

# 1. Generate requirements.txt from Poetry dependencies
FROM python:3.10-slim as requirements

RUN pip install poetry
RUN poetry self add poetry-plugin-export

COPY pyproject.toml ./

RUN poetry export -f requirements.txt -o requirements.txt

# 2. Final app image
FROM python:3.10-slim as app
WORKDIR /opt/dagster/app

# Install requirements
COPY --from=requirements requirements.txt ./
RUN pip install -r requirements.txt

# Copy other files
# COPY ./bitcoin_mining_economics ./

# Code will be exposed on port 4000
EXPOSE 4000

# Start server
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "__init__.py"]